# Generated by Django 4.1 on 2022-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('songtitle', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('dateandtime', models.DateTimeField()),
            ],
        ),
    ]
