# Generated by Django 4.1 on 2022-08-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='dateandtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
